GHC 7.10 support

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,30 +1,24 @@
 env:
-  - lower_bound_dependencies=1 
-    ghc=7.6.1
-  - lower_bound_dependencies=1 
-    ghc=7.8.1
-  - ghc=7.6.1
-  - ghc=7.8.1
-    build_benchmarks=1
-  - postgres_version=8.3.0
-    postgres_integer_datetimes=0
-    ghc=7.8.1
-  - postgres_version=8.3.0
-    postgres_integer_datetimes=1
-    ghc=7.8.1
-  - postgres_version=9.4.0
-    postgres_integer_datetimes=0
-    ghc=7.8.1
+  - ghc=7.6.1  cabal=1.18 benchmarks=1 lower_bound_dependencies=1
+  - ghc=7.6.1  cabal=1.18
+  - ghc=7.8.1  cabal=1.18
+  - ghc=7.10.1 cabal=1.22 tests=1
+  - ghc=7.10.1 cabal=1.22 tests=1 postgres_version=8.3.0 postgres_integer_datetimes=0
+  - ghc=7.10.1 cabal=1.22 tests=1 postgres_version=8.3.0 postgres_integer_datetimes=1
+  - ghc=7.10.1 cabal=1.22 tests=1 postgres_version=9.4.0 postgres_integer_datetimes=1
+  
 
 install:
   # Set up the Shell to treat the semicolon as &&
   - set -o pipefail && set -e
   # Install GHC and Cabal
-  - 
+  -
+    ghc=${ghc=7.10.1}; 
+    cabal=${cabal=1.22};
     travis_retry sudo add-apt-repository -y ppa:hvr/ghc;
     travis_retry sudo apt-get update;
-    travis_retry sudo apt-get install cabal-install-1.18 ghc-$ghc;
-    export PATH=/opt/ghc/$ghc/bin:/opt/cabal/1.18/bin:$PATH;
+    travis_retry sudo apt-get install cabal-install-$cabal ghc-$ghc;
+    export PATH=/opt/ghc/$ghc/bin:/opt/cabal/$cabal/bin:$PATH;
   # Update the Cabal database
   - cabal update
   # Switch to the distro:
@@ -36,7 +30,7 @@ install:
     cd $pkg_name;
   # Install the lower bound dependencies
   - 
-    if [ $lower_bound_dependencies = "1" ];
+    if [ "$lower_bound_dependencies" = "1" ];
     then
       constraint_options=(
         "--constraint=transformers==0.3.*"
@@ -45,19 +39,20 @@ install:
         "--constraint=aeson==0.7.*"
       );
     fi;
-  # Install the library dependencies
-  - cabal install --only-dependencies --reorder-goals
-      ${constraint_options[@]}
-      --enable-tests
-      $([ "$build_benchmarks" = "1" ] && echo "--enable-benchmarks")
   # Install the "haskell-src-exts" implicit dependency
-  - cabal install happy
+  - cabal install happy --reorder-goals --force-reinstalls ${constraint_options[@]}
+  # Install the library dependencies
+  - cabal install --only-dependencies --reorder-goals --force-reinstalls
+      ${constraint_options[@]}
+      $([ "$tests" = "1" ] && echo "--enable-tests")
+      $([ "$benchmarks" = "1" ] && echo "--enable-benchmarks")
   # Build the library
   - cabal build
   # Configure and build the remaining stuff
   - cabal configure 
-      --enable-tests 
-      $([ "$build_benchmarks" = "1" ] && echo "--enable-benchmarks")
+      $([ "$tests" = "1" ] && echo "--enable-tests")
+      $([ "$benchmarks" = "1" ] && echo "--enable-benchmarks")
+      -f doctest
   - cabal build
   # Optionally install an arbitrary PostgreSQL version:
   - 
@@ -93,9 +88,13 @@ install:
 
 
 script:
-  - cabal test --show-details=always ||
-    { 
-      echo "Test failed. Here's the Postgres' log:";
-      sudo cat /usr/local/pgsql/log/main.log;
-      exit 1;
-    }
+  - |
+    if [ "$tests" = "1" ];
+    then
+      cabal test --show-details=always ||
+      { 
+        echo "Test failed. Here's the Postgres' log:";
+        sudo cat /usr/local/pgsql/log/main.log;
+        exit 1;
+      };
+    fi;
